/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
export {}

interface ModuleMap {
  '../../pages-sub/index/index.vue': typeof import('../../pages-sub/index/index.vue')
  '../../pages-sub/plugins/index': typeof import('../../pages-sub/plugins/index')
  '@/pages-sub/plugins/index': typeof import('@/pages-sub/plugins/index')
  [path: string]: any
}

declare global {
  function AsyncImport<T extends keyof ModuleMap>(arg: T): Promise<ModuleMap[T]>
}
