/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
declare module '*?async' {
  const component: any
  export = component
}
declare module '../../pages-sub/index/index.vue?async' {
  const component: typeof import('../../pages-sub/index/index.vue')
  export = component
}
declare module '@/pages-sub/index/index.vue?async' {
  const component: typeof import('@/pages-sub/index/index.vue')
  export = component
}
